# Generated by Django 5.1.7 on 2025-03-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status_alter_orderstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(default='preparing', max_length=20),
        ),
    ]
